apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deploy
  labels:
    app: healthcareapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcareapp
  template:
    metadata:
      labels:
        app: healthcareapp
    spec:
      containers:
      - name: health-care-container
        image: manjunathachar/healthcareapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: health-service
  labels:
    app: healthcareapp
spec:
  selector:
    app: healthcareapp
  type: NodePort
  ports:
  - nodePort: 31447
    port: 8979
    targetPort: 8979


