name: Deploy to Azure Containerized Web App

on:
  push:
    branches:
      - master  # Adjusted to use the feature branch, adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify Java version
          distribution: 'adoptopenjdk'  # Specify Java distribution (e.g., 'adoptopenjdk', 'zulu', etc.)

      - name: Build, package, and test with Maven
        run: |
          mvn clean package test  # Clean, build the project, and run tests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Make sure this secret is set in your GitHub secrets

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_NAME }}  # Make sure this secret is set in your GitHub secrets
          password: ${{ secrets.ACR_PASSWORD }}   # Make sure this secret is set in your GitHub secrets
          registry: ${{ secrets.REGISTRY_NAME }}.azurecr.io

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/healthcare-web-app:latest .
          docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/healthcare-web-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEB_APP_NAME }}  # Make sure this secret is set in your GitHub secrets
          slot-name: production
          images: ${{ secrets.REGISTRY_NAME }}.azurecr.io/healthcare-web-app:latest
