name: Deploy to Azure Containerized Web App

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.REGISTRY_NAME }}.azurecr.io

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/healthcare-web-app:latest .
          docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/healthcare-web-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEB_APP_NAME }}
          slot-name: production
          images: ${{ secrets.REGISTRY_NAME }}.azurecr.io/healthcare-web-app:latest`
